# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Jot' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Jot
  source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '8.0'
  use_frameworks!

  pod 'FontAwesome.swift'

  pod 'Hue'

  pod 'SideMenu', '~> 2.3.4'

  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'GoogleSignIn'

  target 'JotTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JotUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
